# Generated by Django 6.0.6 on 2026-06-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
